### ISSUE TITLE
Unable to Open https rss feeds

### ISSUE THREAD

**Issue by rickyphewitt** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#86]
2 shows Ask Noah and LAN have audio https feeds. The plugin fails to load the episode feed when audio mode for these shows.

Appears to be an SSL issue. Per the youtube plugin's issue tracker. (Have not verified it is the same issue): https://github.com/jdf76/plugin.video.youtube/issues/14

Exception: 

` NOTICE: https://asknoah.fireside.fm/rss
07:55:36 T:139909930395392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 0] Error>
                                            Traceback (most recent call last):
                                              File "/home/ricky/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 288, in <module>
                                                index(NAME, URL, PAGE)
                                              File "/home/ricky/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 96, in index
                                                feedParser.parseXML()
                                              File "/home/ricky/.kodi/addons/plugin.video.jupiterbroadcasting/feed_parser.py", line 29, in parseXML
                                                data = self._readUrl()
                                              File "/home/ricky/.kodi/addons/plugin.video.jupiterbroadcasting/feed_parser.py", line 40, in _readUrl
                                                return urllib2.urlopen(self.feed_url)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 0] Error>
                                            -->End of Python script error report<--
`

**Comment by rickyphewitt** [comment]
This has been fixed with above commits. In short moved to the requests library over urllib/urllib2
