### ISSUE TITLE
requests not found

### ISSUE THREAD

**Issue by RobLoach** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#94]
```
21:03:30.341 T:140420875208448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 12, in <module>
                                                from feed_parser import FeedParser
                                              File "/storage/.kodi/addons/plugin.video.jupiterbroadcasting/feed_parser.py", line 6, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--
21:03:30.370 T:140423541763392   ERROR: GetDirectory - Error getting plugin://plugin.video.jupiterbroadcasting/
```

**Comment by RobLoach** [comment]
FIxed
