### ISSUE TITLE
Most Recent list failing. 

### ISSUE THREAD

**Issue by develroo** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#99]
I assume it is because of the changes to the separate RSS feeds now.

```
11:10:52.910 T:2813858560   ERROR: Jupiter Broadcasting Parsing Failure. Provide this log to https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting : cannot concatenate 'str' and 'NoneType' objects
11:10:52.913 T:2813858560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 287, in <module>
                                                index(NAME, URL, PAGE)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 121, in index
                                                info['plot'] = feedParser.parsePlot(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/feed_parser.py", line 98, in parsePlot
                                                plot = ml_stripper.html_to_text(description.string)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/ml_stripper.py", line 18, in html_to_text
                                                s.feed(html)
                                              File "/usr/lib/python2.7/HTMLParser.py", line 116, in feed
                                                self.rawdata = self.rawdata + data
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--

```

**Comment by RobLoach** [comment]
What version of Kodi are you on?

**Comment by RobLoach** [comment]
What podcast did you browse to get that error?

**Comment by develroo** [comment]
It is the vero 4K Media centre box which tracks the kodi repo. 

So currently the 04-2018 build or 17.6 
```

20:51:14.893 T:4081861200  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:51:14.894 T:4081861200  NOTICE: -----------------------------------------------------------------------
20:51:14.894 T:4081861200  NOTICE: Starting Kodi (17.6). Platform: Linux ARM (Thumb) 32-bit
20:51:14.894 T:4081861200  NOTICE: Using Release Kodi x32 build (version for Vero)
20:51:14.894 T:4081861200  NOTICE: Kodi compiled Apr 25 2018 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.30 (264478)
20:51:14.894 T:4081861200  NOTICE: Running on Open Source Media Center 2018.04-1, kernel: Linux ARM 32-bit version 3.14.29-93-osmc
20:51:14.894 T:4081861200  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
20:51:14.894 T:4081861200  NOTICE: Host CPU: AArch64 Processor rev 4 (aarch64), 4 cores available
20:51:14.894 T:4081861200  NOTICE: ARM Features: Neon disabled
20:51:14.894 T:4081861200  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
20:51:14.894 T:4081861200  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
20:51:14.894 T:4081861200  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
20:51:14.894 T:4081861200  NOTICE: special://masterprofile/ is mapped to: /home/osmc/.kodi/userdata
20:51:14.894 T:4081861200  NOTICE: special://envhome/ is mapped to: /home/osmc
20:51:14.894 T:4081861200  NOTICE: special://home/ is mapped to: /home/osmc/.kodi
20:51:14.894 T:4081861200  NOTICE: special://temp/ is mapped to: /home/osmc/.kodi/temp
20:51:14.894 T:4081861200  NOTICE: special://logpath/ is mapped to: /home/osmc/.kodi/temp
20:51:14.894 T:4081861200  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
20:51:14.894 T:4081861200  NOTICE: Local hostname: osmc-Algernon
20:51:14.894 T:4081861200  NOTICE: Log File is located: /home/osmc/.kodi/temp//kodi.log
20:51:14.894 T:4081861200  NOTICE: -----------------------------------------------------------------------

```


It is not on the podcasts themselves. Only on Most Recent. Though it does  look like the podcasts are updating properly so for example the last Ask Noah was 63, the last Linux Action News was 51 etc. 

Thanks.

**Comment by rickyphewitt** [comment]
I'll see if I can repro this tomorrow.

**Comment by rickyphewitt** [comment]
@develroo,

What version of the JB plugin do you have?

**Comment by develroo** [comment]
version="3.6.2"

**Comment by rickyphewitt** [comment]
I just tested with 3.6.2 and an older version of kodi and did not receive the error.

@develroo,

Is it consistent or intermittent?

**Comment by develroo** [comment]
Well started a few weeks back but it is consistent now. Sure.. Every time I select most recent it will produce that error. Live works, Archive works All the Current shows seem to work. Are there any legacy settings which maybe causing this? I have had the JB plugin for years on various systems never had this problem on one. 

This is the same error with debug logging turned on.

```
10:49:14.285 T:4076089936   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.jupiterbroadcasting/?mode=1&name=%5b%20Most%20Recent%20%5d&page=0&url=http%3a%2f%2ffeeds2.feedburner.com%2fAllJupiterVideos%3fformat%3dxml)
10:49:14.285 T:4076089936   DEBUG:   ParentPath = [plugin://plugin.video.jupiterbroadcasting/]
10:49:14.329 T:3394233088   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.jupiterbroadcasting] took 44 ms
10:49:14.332 T:3795841792   DEBUG: StartScript - calling plugin Jupiter Broadcasting('plugin://plugin.video.jupiterbroadcasting/','2','?mode=1&name=%5b%20Most%20Recent%20%5d&page=0&url=http%3a%2f%2ffeeds2.feedburner.com%2fAllJupiterVideos%3fformat%3dxml')
10:49:14.333 T:3177247488   DEBUG: Thread LanguageInvoker start, auto delete: false
10:49:14.333 T:3177247488    INFO: initializing python engine.
10:49:14.333 T:3177247488   DEBUG: CPythonInvoker(21, /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py): start processing
10:49:14.573 T:3177247488   DEBUG: -->Python Interpreter Initialized<--
10:49:14.574 T:3177247488   DEBUG: CPythonInvoker(21, /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py"
10:49:14.575 T:3177247488   DEBUG: CPythonInvoker(21, /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting:/home/osmc/.kodi/addons/script.module.beautifulsoup/lib:/home/osmc/.kodi/addons/script.module.certifi/lib:/home/osmc/.kodi/addons/script.module.chardet/lib:/home/osmc/.kodi/addons/script.module.idna/lib:/home/osmc/.kodi/addons/script.module.requests/lib:/home/osmc/.kodi/addons/script.module.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
10:49:14.575 T:3177247488   DEBUG: CPythonInvoker(21, /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py): entering source directory /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting
10:49:14.575 T:3177247488   DEBUG: CPythonInvoker(21, /home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py): instantiating addon using automatically obtained id of "plugin.video.jupiterbroadcasting" dependent on version 2.25.0 of the xbmc.python api
10:49:14.787 T:4076089936   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:49:14.789 T:4076089936   DEBUG: LIRC: Update - NEW at 86344:160 0 KEY_OK_UP linux-input-layer (KEY_OK_UP)
10:49:21.006 T:3177247488   ERROR: Jupiter Broadcasting Parsing Failure. Provide this log to https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting : cannot concatenate 'str' and 'NoneType' objects
10:49:21.009 T:3177247488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 287, in <module>
                                                index(NAME, URL, PAGE)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/default.py", line 121, in index
                                                info['plot'] = feedParser.parsePlot(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/feed_parser.py", line 98, in parsePlot
                                                plot = ml_stripper.html_to_text(description.string)
                                              File "/home/osmc/.kodi/addons/plugin.video.jupiterbroadcasting/ml_stripper.py", line 18, in html_to_text
                                                s.feed(html)
                                              File "/usr/lib/python2.7/HTMLParser.py", line 116, in feed
                                                self.rawdata = self.rawdata + data
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
10:49:21.031 T:4076089936   DEBUG: ------ Window Init (DialogNotification.xml) ------
10:49:21.586 T:3177247488    INFO: Python script stopped
10:49:21.587 T:3177247488   DEBUG: Thread LanguageInvoker 3177247488 terminating
10:49:21.597 T:4076089936   ERROR: GetDirectory - Error getting plugin://plugin.video.jupiterbroadcasting/?mode=1&name=%5b%20Most%20Recent%20%5d&page=0&url=http%3a%2f%2ffeeds2.feedburner.com%2fAllJupiterVideos%3fformat%3dxml
10:49:21.598 T:4076089936   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jupiterbroadcasting/?mode=1&name=%5b%20Most%20Recent%20%5d&page=0&url=http%3a%2f%2ffeeds2.feedburner.com%2fAllJupiterVideos%3fformat%3dxml) failed
10:49:21.598 T:4076089936   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.jupiterbroadcasting/)
10:49:21.599 T:4076089936   DEBUG:   ParentPath = [addons://sources/video]
10:49:21.601 T:4076089936   DEBUG: Loading items: 11, directory: plugin://plugin.video.jupiterbroadcasting/ sort method: 0, ascending: false
10:49:21.669 T:3804230400   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.jupiterbroadcasting] took 70 ms
10:49:21.674 T:3177247488   DEBUG: Thread BackgroundLoader start, auto delete: false
10:49:21.682 T:4076089936   DEBUG: [Warning] CGUITextureManager::GetTexturePath: could not find texture 'noop'
10:49:21.690 T:3177247488   DEBUG: Thread BackgroundLoader 3177247488 terminating

```
Does that help any?

**Comment by rickyphewitt** [comment]
Can confirm I'm seeing the same error on Kodi 17.3. I'll dig in and take a look :)

**Comment by rickyphewitt** [comment]
Ok I think I've narrowed it down. Appears one of the unfilter episodes's description contains back ticks instead of an Apostrophe: 
`The memo’s are out, the interviews are in, and we've read the book. It’s our take on former FBI Director James Comey’s moral crusade.`

**Comment by develroo** [comment]
Hmmm maybe map it to unicode then and then escape it ? Would help if you ever get any accents or foreign chars in titles.

**Comment by develroo** [comment]
Perhaps a  workaround like [this](https://github.com/kurtmckee/feedparser/issues/101#issuecomment-380472168) might work? Granted JB really need to fix their titles but given than some of the published services don't allow you to do that, then I feel it is worth catching those edge cases so functionality for the app is not broken.

**Comment by rickyphewitt** [comment]
Yea I was playing around with something similar. I should have a bit of time to work on it this weekend.

**Comment by rickyphewitt** [comment]
Also it appears you can't just clone a git repo into the addons folder for dev/testing. I'm currently trying to figure out the 'new' way of developing addons and having kodi recognize the plugin so I can make changes on the fly and test :)

**Comment by RobLoach** [comment]
>it appears you can't just clone a git repo into the addons folder for dev/testing

I usually download for the Addons Repository through Kodi, and then quit Kodi, delete the addon, and clone the repo where it downloaded it to.

**Comment by rickyphewitt** [comment]
@RobLoach,

That seems to have worked. I was doing a symlink before and kodi did not seem to like that.

**Comment by rickyphewitt** [comment]
In the end I just had to set the default encoding. 
@develroo,
If you have time pull down the commit in PR https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/pull/100 and see if it resolves the issue on your 4K Media centre box.

**Comment by develroo** [comment]
Ok will do. Thanks. 


EDIT: 

Yup that fixed it. No more crashing when using Most Recent.  Thanks!

**Comment by rickyphewitt** [comment]
Awesome! Sorry it took so long for such a simple change :)
